# Generated by Django 6.0.4 on 2026-04-30 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinValueValidator(12)]),
        ),
    ]
