# Generated by Django 6.0.4 on 2026-04-30 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_company_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('[0-9]{12}')]),
        ),
    ]
